name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: mohammedshibiyas
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push snake files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update contribution snake"
          add: "dist/*.svg"
